[package]
name = "ht"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy-tokio-tasks = "*"


[dependencies.bevy]
version = "*"
features = ["dynamic_linking", "detailed_trace"]

[dependencies.ht-core]
path = "../ht-core"
